version: "3.4"

services:
  mysql:
    container_name: mysql
    image: mariadb:latest
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    tty: true

  nginx:
    container_name: nginx
    build: ./nginx
    env_file: .env
    ports:
      - "80:80"
    volumes:
      # Projects files
      - ${WEBSITES}:/var/www/html:rw,delegated
      # Websites configuration
      - ./nginx/site-available:/etc/nginx/conf.d/:ro
      # Logs
      - ./nginx/log:/var/log/nginx
    depends_on:
      - php
    networks:
      - php
    tty: true
    links:
      - php

  php:
    container_name: php
    build:
      context: ./php
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      # Projects files
      - ${WEBSITES}:/var/www/html:rw,delegated
      # Custom configuration
      - ./php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      # SSH keys
      - ~/.ssh:/root/.ssh:ro
    depends_on:
      - mysql
    networks:
      - php
    tty: true
    links:
      - mysql

volumes:
  mysql: {}

networks:
    php:
